import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Immanuvel",
  icons: {
    icon: "/favicon.png",
  },
  keywords: ["Immanuvel", "Next.js", "React", "TypeScript","Portfolio"],
  authors: [
    {
      name: "Immanuvel",
    },
  ],
  creator: "Immanuvel",
  publisher: "Immanuvel",
  description: "Generated by create next app",
  verification: {
    google: "mPfU4gmz2hZbYQTnwbs8gbWsMCbLtWzzZ6l1uSqatAQ",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <head>
        <meta name="google-site-verification" content="mPfU4gmz2hZbYQTnwbs8gbWsMCbLtWzzZ6l1uSqatAQ" />
      </head>
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
