import type { Metadata } from "next";
import { Geist, Geist_Mono, Livvic } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { PageLoadingProvider } from "@/components/providers/page-loading-provider";
import Header from "@/components/Header";
import ErrorBoundary from "@/components/ErrorBoundary";
// Local font imports
import { elegantScript, pacifico } from './fonts';

// Import the client component directly
import WelcomePopup from '@/components/WelcomePopupClient';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const livvic = Livvic({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-livvic',
});

export const metadata: Metadata = {
  title: "Immanuvel",
  icons: {
    icon: "/favicon.png",
  },
  keywords: ["Immanuvel", "Next.js", "React", "TypeScript","Portfolio"],
  authors: [
    {
      name: "Immanuvel",
    },
  ],
  creator: "Immanuvel",
  publisher: "Immanuvel",
  description: "Generated by create next app",
  verification: {
    google: "mPfU4gmz2hZbYQTnwbs8gbWsMCbLtWzzZ6l1uSqatAQ",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${livvic.variable} ${pacifico.variable} antialiased`} suppressHydrationWarning>
      <head>
        <meta name="google-site-verification" content="mPfU4gmz2hZbYQTnwbs8gbWsMCbLtWzzZ6l1uSqatAQ" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${livvic.variable} ${elegantScript.variable} bg-gradient-to-b from-gray-950 via-gray-900 to-gray-950 text-gray-100 min-h-screen flex flex-col`}>
        <PageLoadingProvider>
          <ErrorBoundary>
            <Providers>
              <Header />
              <main className="flex-1">
                {children}
              </main>
              <WelcomePopup />
            </Providers>
          </ErrorBoundary>
        </PageLoadingProvider>
      </body>
    </html>
  );
}
